replicaCount: 2
image:
  repository: 165690630824.dkr.ecr.eu-central-1.amazonaws.com/lesson-7-ecr
  tag: b9d98df
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000
configMap:
  name: django-app-config
  data:
    DEBUG: "False"
    ALLOWED_HOSTS: "a28e805ef713a46d6a45961e1aa01977-363344798.eu-central-1.elb.amazonaws.com"
    DJANGO_SETTINGS_MODULE: "config.settings"
    PORT: "8000"
externalDatabase:
  host: "django-db.c3m480c421j3.eu-central-1.rds.amazonaws.com"
  port: "5432"
  name: "app"
secret:
  create: false
  name: django-app-secret
  data:
    SECRET_KEY: ""
    DB_USER: ""
    DB_PASSWORD: ""
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
