apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  DEBUG: {{ .Values.configMap.data.DEBUG | quote }}
  ALLOWED_HOSTS: {{ .Values.configMap.data.ALLOWED_HOSTS | quote }}
  DJANGO_SETTINGS_MODULE: {{ .Values.configMap.data.DJANGO_SETTINGS_MODULE | quote }}
  PORT: {{ .Values.configMap.data.PORT | quote }}
  DB_HOST: {{ required "externalDatabase.host is required" .Values.externalDatabase.host | quote }}
  DB_PORT: {{ .Values.externalDatabase.port | quote }}
  DB_NAME: {{ required "externalDatabase.name is required" .Values.externalDatabase.name | quote }}
